wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.32.0.dev0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1695671711.800403
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 1
      - 23
      4: 3.10.11
      5: 0.15.4
      6: 4.32.0.dev0
      8:
      - 5
